### ISSUE TITLE
bug，旋转的时候

### ISSUE THREAD

**Issue by icharlie2014** [gsdios/SDAutoLayout#10]
![14390825-2d86-45d9-a7b6-d888f2c1f0fe](https://cloud.githubusercontent.com/assets/8463936/11950167/f694b686-a8c0-11e5-8514-b2251e775a94.png)

command + → 多按几次

**Comment by gsdios** [comment]
哪个部分出问题了呢？

**Comment by gsdios** [comment]
加入 SDAutoLayout交流群了吗，没有的话加入下（QQ群：497140713）

**Comment by icharlie2014** [comment]
我重新传了图。你看下

**Comment by gsdios** [comment]
看不出 什么bug，你直接描述下是哪里出现什么问题了

**Comment by icharlie2014** [comment]
![24a08033-f0c1-4158-8190-00bd7ef54a54](https://cloud.githubusercontent.com/assets/8463936/11950436/34243484-a8c3-11e5-8ffc-8fb0bc0623f8.png)

就是旋转啊command + → 模拟器旋转出现这个我旋转了还是维持原来那个横屏的状态，正确的不应该是上面这个截图吗 @gsdios

**Comment by gsdios** [comment]
模拟器的旋转就是 这样的 ，有的方向是不支持的就停留在上一个方向，你继续旋转就会恢复了的
