### ISSUE TITLE
请问，cell中的其他控件是通过xib的自动布局设置布局的，可以混合使用sdautolayout么

### ISSUE THREAD

**Issue by DanielYQ** [gsdios/SDAutoLayout#104]
如题，我的cell是用xib拖拽出来的，但其中一个lable需要自适应高度，可以这个label使用sdautolayout代码布局，其他控件使用xib的自动布局吗？
非常感谢！

**Comment by gsdios** [comment]
如果你用了其他布局方式的控件 不参照这个label布置过约束就没有问题的
