### ISSUE TITLE
竖屏转横屏后，cell的高度貌似不太正确？

### ISSUE THREAD

**Issue by qimuya3** [gsdios/SDAutoLayout#12]
竖屏转横屏后，cell的高度貌似不太正确？我使用demo发现的。

**Comment by gsdios** [comment]
demo几呢？截图 我看下

**Comment by qimuya3** [comment]
![landspace](https://cloud.githubusercontent.com/assets/12780790/12082738/30515fbc-b2d2-11e5-9523-4e237e6776f5.PNG)
![Uploading portrait.PNG…]()
你可以观察：cell底部的“一分钟前”与底部的间距，横屏后明显变宽。

**Comment by qimuya3** [comment]
![portrait](https://cloud.githubusercontent.com/assets/12780790/12082834/cebc2186-b2d3-11e5-8707-12d076771b9d.PNG)

**Comment by gsdios** [comment]
下载 最新代码 再看下

**Comment by qimuya3** [comment]
已经没问题，非常感谢。做得越来越好了。
