### ISSUE TITLE
崩溃在- (void)sd_layoutSubviews

### ISSUE THREAD

**Issue by qggz0524** [gsdios/SDAutoLayout#124]
在这个方法崩溃，无法定位

**Comment by cheniuiOSloved** [comment]
me too。 it works well on simulator ,but when i debug on iphone ,it sometimes will crash mostly.I use with masonry either。

**Comment by q563469** [comment]
me too。 it works well on simulator ,but when i debug on iphone ,it sometimes will crash mostly.I use with masonry either

**Comment by LoveZYForever** [comment]
我能说经常的么?有时候项目一运行就蹦在这里

**Comment by gsdios** [comment]
如果你的项引入了sd库，那么在你的所有view（不管是否使用了sd布局）调用layoutSubviews方法时会走sd_layoutSubviews内部，如果此view没有使用sd布局就直接调用默认的或者你自己实现的layoutSubviews方法而sd不会做任何处理，换言之，如果crash在这里可能是因为你的layoutSubviews内部逻辑问题

**Comment by LoveZYForever** [comment]
放你妈的猪皮
