### ISSUE TITLE
 [cell useCellFrameCacheWithIndexPath:indexPath tableView:tableView];设置这个方法后Label的高度自适应就不好使了

### ISSUE THREAD

**Issue by LiuYuHangNB** [gsdios/SDAutoLayout#126]
我用的是这个方法进行的高度自适应
- (CGFloat)cellHeightForIndexPath:(NSIndexPath *)indexPath model:(id)model keyPath:(NSString *)keyPath cellClass:(Class)cellClass contentViewWidth:(CGFloat)contentViewWidth;

**Comment by gsdios** [comment]
参照demo再熟悉下sd用法
