### ISSUE TITLE
ipad 启动挂在 sd_layoutSubviews

### ISSUE THREAD

**Issue by ilioner** [gsdios/SDAutoLayout#134]
如题，iphone启动是一切正常的  ipad启动一直出现在执行sd_layoutSubviews  且cpu占用一直在95%+，求高手给出建议

**Comment by ilioner** [comment]
补充:ipad启动一直卡在启动界面  卡一会就挂了，卡启动画面期间执行情况如上所述

**Comment by jcxc** [comment]
貌似都没人解决这里的问题吧。。。

**Comment by gsdios** [comment]
你的所有view在调用layoutsubviews的时候都会经过 sd_layoutSubviews，先看下你的view在调用layoutsubviews时也没有发生死循环
