### ISSUE TITLE
UITableviewCell高度自适应时，偶尔会出现主线程卡死

### ISSUE THREAD

**Issue by gentleboy** [gsdios/SDAutoLayout#147]
在使用SDAutolayout进行TableviewCell的高度自适应布局时，偶尔会出现界面卡死的情况，但是很难复现，最近测试的时候只出现过几次。当出现界面卡死的时候，监测到内存以大约4M/s的速度不断增长，并且主线程在反复执行[UIView sd_layoutSubviewsHandle]这个函数，调用栈截图如下：
![2016-11-24 22 43 41](https://cloud.githubusercontent.com/assets/10232677/20602291/902e5e10-b297-11e6-9563-c3c6403036c8.png)
Cell的样式并不复杂，效果图如下：
![img_0073](https://cloud.githubusercontent.com/assets/10232677/20602446/31d993c4-b298-11e6-9624-c89511c3412b.PNG)

求大神帮忙看一下是什么原因导致这种现象产生~

**Comment by gsdios** [comment]
button的约束设置代码贴出来下
