### ISSUE TITLE
使用SD遇到的一些问题

### ISSUE THREAD

**Issue by mrhyh** [gsdios/SDAutoLayout#151]
使用SD遇到的一些问题（请作者勿直接删除，我留下这个只是为了跟大家讨论下的）：
    _countDownView.sd_layout //_countDownView是一个xib自定义View
    //.centerYEqualToView(_seckillImageView) //这是无效的
    .topEqualToView(_seckillImageView)
    .leftSpaceToView(_seckillImageView,40) //这里也是无效的，40是直接从父视图的最左边开始的
    .widthIs(65)
    .heightIs(labelH);

如果_countDownView是纯代码的view，就没有问题

**Comment by gsdios** [comment]
xib关掉自动布局开关了吗

**Comment by mrhyh** [comment]
没有，SD和xib的自动布局不能并存哇？

**Comment by gsdios** [comment]
要么使用sd的约束，要么使用系统的约束，两者共用可能会出现问题
