### ISSUE TITLE
关于点击别人评论的label给予回复的问题

### ISSUE THREAD

**Issue by LittleLydia** [gsdios/SDAutoLayout#153]
高大神，我看到你已经在代码里写了部分关于回复别人对朋友圈的评论的部分代码，有点不明白为什么你没有实现这个功能ing，是因为后面遇到bug了嚒？

我尝试修改了部分代码让评论可以实现，有点可惜的是评论是可以评论了，就是一直都有点问题，要么就是评论偶尔显示在不同的cell的评论下，要么偶尔显示不出来；当时你也是遇到这样的问题了吗？

**Comment by gsdios** [comment]
这个功能在gsd_weixin的demo上有实现，后来合入代码的时候冲掉了，你可以看下代码提交记录上有没有保留

**Comment by LittleLydia** [comment]
谢谢大神回复，找到了耶；竟然会冲掉，这么方便实用的功能！
完整回复评论功能的那个版本的链接：[(https://github.com/gsdios/GSD_WeiXin/tree/311d7a4bc537c8c84424794e84ad023537ac01be)]
ps：大神，选择用UIlabel而没有用UITableView也是因为在cell上嵌套一个UITableView，外面那层cell的高度会因为重用机制变得掌控不了吗？
