### ISSUE TITLE
在原来model中加了一个字段，导致报错，提示为尊徐coding协议

### ISSUE THREAD

**Issue by XiaoyouPrience** [gsdios/SDAutoLayout#156]
主要就是这里了，sd你看一下，求解
![ea8ccef3-daed-4b42-9b1c-889bf75430bd](https://cloud.githubusercontent.com/assets/15156910/21513347/45c1bb04-ccf2-11e6-986e-bbf7c1563231.png)

**Comment by gsdios** [comment]
这个是你有对model做持久化操作的原因吧。
