### ISSUE TITLE
label的字体变模糊了

### ISSUE THREAD

**Issue by shunFSKi** [gsdios/SDAutoLayout#159]
用sdautolayout布局后，为什么label的字体会变模糊了？

**Comment by gsdios** [comment]
确定和sd有关系，用系统自带api测试下效果看下，如果只有sd有问题的话在联系下我。

**Comment by shunFSKi** [comment]
是的，因为我的项目是部分页面使用sd布局，其他的之前使用的masonry，对比一看很明显，最近发现之后检查了一下，的确使用了sd的都会糊，我看了一下demo好像没有问题，目前还不知道是怎么回事

**Comment by shunFSKi** [comment]
还有就是，使用sd布局的label设置行数会失效？
