### ISSUE TITLE
如果在cell里面有UIView的嵌套，该如何做自适应？

### ISSUE THREAD

**Issue by JackWolffffff** [gsdios/SDAutoLayout#16]
cell里面包含了一个UIView A，A的高度不确定，A里面又包含了两个UIView B， C，其中B的高度动态变化，我在自定义cell类里调用了A的自适应高度方法，同时也调用了cell的自适应高度方法，然后cpu就飙升到100%了

**Comment by gsdios** [comment]
cell发给我看下，gsdios@126.com，新建SDAutoLayoutQQ交流群：497140713，可以加入下
