### ISSUE TITLE
label.isAttributedContent 设置后在小于一行文字的时候自动左对齐，无法做到居中！

### ISSUE THREAD

**Issue by kangzhongwei** [gsdios/SDAutoLayout#165]
设置富文本的样式，在已经设置label文字居中的属性， 在大于一行的情况下label文字可以居中，但小于的时候就自动左对齐。可以看到在打开这个属性的时候label是 自适应的，设置的右边距是没有执行的，是否是我没有使用正确？

**Comment by gsdios** [comment]
富文本用到sizetofit方法计算label的size，这个方法会导致不足一行时label宽度等于文字宽度，尝试设置一下minWidth试下

**Comment by kangzhongwei** [comment]
您好，问题已解决，谢谢，希望能在demo中增加minWidthIs和maxWidthIs等的使用注意事项，以便正好的使用自动布局，非常感谢您的这个自动布局！

**Comment by doubleJJJJ** [comment]
> 您好，问题已解决，谢谢，希望能在demo中增加minWidthIs和maxWidthIs等的使用注意事项，以便正好的使用自动布局，非常感谢您的这个自动布局！

请问这个问题是怎么解决呢？
         label.sd_layout
        .autoHeightRatio(0)
        .leftSpaceToView(self.contentView, 34)
        .topSpaceToView(titleLab, 35)
        .rightSpaceToView(self.contentView, 34)
        .minWidthIs(300);
        我已经设置了minWidthIs，可是单行富文本label的宽度仍然是自适应，并且没有居中对齐，是哪里的问题呢？
