### ISSUE TITLE
isAttributedContent 的问题

### ISSUE THREAD

**Issue by aimm** [gsdios/SDAutoLayout#166]
1.  先设置  _priceLabel.isAttributedContent = YES ；
2. 布局完成后，设置 [_priceLabel setMaxNumberOfLinesToShow:1]; 2行就没事 1行就有问题了
3. 设置 _priceLabel.attributedText = attributedPriceString;
经过以上3步，会使 label 位置向上移动，去掉 最大行数限制或行数>1就没事了，求解

**Comment by gsdios** [comment]
富文本不能设置最大显示行数，因为富文本的行高和行间距都是可以自己定义的，需要自己计算具体行高然后设置maxHeight而不是设置最大显示行数
