### ISSUE TITLE
minWidthIs 不起作用

### ISSUE THREAD

**Issue by 1617176084** [gsdios/SDAutoLayout#167]
![2d5f3061-383d-42ad-97a2-3ebec47f1925](https://cloud.githubusercontent.com/assets/7008899/23055037/73afaa18-f51e-11e6-963c-5a6203405335.png)
当我是用lab自动宽度的时候时，最小宽度约束不起作用，
minWidthIs（120） 这个不起作用

**Comment by gsdios** [comment]
setSingleLine。。。MaxWidth中的参数值最终是多少呢？
