### ISSUE TITLE
NSMutableAttributedString字符串居中问题

### ISSUE THREAD

**Issue by PreAnti** [gsdios/SDAutoLayout#168]
![623107d7 403bcb8e14 bbe39a58_recompress](https://cloud.githubusercontent.com/assets/9427611/23156171/db2a3cd2-f850-11e6-8a94-c4106a62a55f.jpg)
你好，如上图所示是你们SDAutoLayoutDemo里DemoVC4.m里的源码，红框里是我自己加进去的，但是运行起来后文字并没有居中显示。如下图所示：
![3090ae3c9f4318414e39107fcce9e0f8](https://cloud.githubusercontent.com/assets/9427611/23156214/fce3e5bc-f850-11e6-92bb-2115a4575963.png)

**Comment by gsdios** [comment]
sd中富文本布局用到了系统的sizeToFit函数，label自身的宽度会根据文本实际宽度调整导致看起来文字好像不居中，可以加上minWidth约束限制文本的宽度
