### ISSUE TITLE
文本计算cpu 的消耗

### ISSUE THREAD

**Issue by TuDoudong** [gsdios/SDAutoLayout#177]
CGRect rect = [label.text boundingRectWithSize:CGSizeMake(MAXFLOAT, label.height_sd) options:NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName : label.font} context:nil];

文本计算消耗了大量的cpu 资源 达到1008x 请问有什么可以优化的

**Comment by TuDoudong** [comment]
然而这个是SD里面的计算方法。。。

**Comment by MrWilsonXu** [comment]
我瞧瞧

**Comment by MrWilsonXu** [comment]
CGRect rect = [label.text boundingRectWithSize:CGSizeMake(label.width_sd, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName : label.font} context:nil];
这才是人家的源码

**Comment by MrWilsonXu** [comment]
![2017-03-31 4 26 57](https://cloud.githubusercontent.com/assets/13956449/24542634/f175a9b2-162e-11e7-9d21-12279dfee9e2.png)
你搞错了  我之前也遇到过  layout添加不正确  cpu会耗死

**Comment by TuDoudong** [comment]
<img width="839" alt="2017-03-31 4 31 02" src="https://cloud.githubusercontent.com/assets/13363667/24542839/c5aa366c-162f-11e7-959e-0a3b615e0875.png">
是这个方法，这个跟layout 添加方式没关系吧，都要进行处理的

**Comment by TuDoudong** [comment]
我明白了  if (view.sd_maxWidth && (model.rightSpaceToView || model.rightEqualToView)) { // 靠右布局前提设置
        [self layoutAutoWidthWidthView:view model:model];
        view.fixedWidth = @(view.width_sd);
    }

满足这些条件会调用这个方法的

**Comment by MrWilsonXu** [comment]
也就是说，以右边界为layout参考点，自动设置width

**Comment by TuDoudong** [comment]
非常感谢你的回答

**Comment by TuDoudong** [comment]
非常感谢你的解答
