### ISSUE TITLE
计算cell高度，无法使用UITableViewAutomaticDimension

### ISSUE THREAD

**Issue by wzi90921** [gsdios/SDAutoLayout#181]
场景：tableview 有多种cell，有的使用xib-autolayout布局，有的使用sdautolayout布局；
xib-autolayout布局 使用
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 44;
但是sdautolayout布局的cell，无法正常显示；
如果使用sdautolayout提供的计算cell高度的方法，xib-autolayout布局布局的cell 也无法正常显示。
是否有什么方式可以兼容此两种布局的cell呢

**Comment by gsdios** [comment]
sd是自己实现的自动布局算法通过修改frame实现自动布局不可和系统约束混用
