### ISSUE TITLE
UITableView(SDAutoTableViewCellHeight) sd_reloadData闪退

### ISSUE THREAD

**Issue by Liqiankun** [gsdios/SDAutoLayout#182]
![2017-04-10 7 17 58](https://cloud.githubusercontent.com/assets/11532418/24859518/806e52c6-1e23-11e7-8f61-c5bba1ef9417.png)

**Comment by gsdios** [comment]
sd_reloadData 就是[你的tableview reloadData]在执行时出错了，sd_reloadData指向的是你原来的reloadData的实现，你的所有reloadData调用都会在方法堆栈里最终显示为sd_reloadData，但是sd并没有对你的函数做额外处理，就是说假如你没有导入sd库的话，crash堆栈就会显示为reloadData
