### ISSUE TITLE
想请教下setupAutoHeightWithBottomView的一些问题

### ISSUE THREAD

**Issue by zj-insist** [gsdios/SDAutoLayout#183]
我想给一个cell定制两种以上样式
几种样式的bottomView都不相同，通过cellStyle的setter方法重设布局
但我发现，只要在初始化的时候默认一种样式，后面不管怎么修改样式，cell的高度都是初始化样式的高度
感觉是setupAutoHeightWithBottomView只在第一次设置时候有效，后面无法重复设置，请问有没有什么方法可以重复设置？

**Comment by gsdios** [comment]
每次都会根据最新的bottomview计算cell高度的，详细请参照demo9
