### ISSUE TITLE
A bug happened to me, share it here, about: UIView (SDAutoLayout)  + (void)load

### ISSUE THREAD

**Issue by fallending** [gsdios/SDAutoLayout#185]
https://github.com/BinaryArtists/not-just-code/blob/master/ios/oc/load%26initialize.md

该问题，导致sd_layoutSubviews实效。嘿嘿，并非框架有问题，但组合使用时，受其他代码牵连。

上述markdown中，如果有表述错误，还请不吝指正。

**Comment by gsdios** [comment]
是的，这个问题之前有开发者在使用sd库的时候遇到过，就是部分开发者在load方法中做swizzling操作时手动调用super的load方法导致，这种做法是不规范的。其实解决此问题也可以通过dispatch once保护自己实现的swizzling操作
