### ISSUE TITLE
Xcode版本问题

### ISSUE THREAD

**Issue by weixianlove** [gsdios/SDAutoLayout#19]
// >>>>>>>>>>>>>> 多cell情景下调用以下方法(详细用法见demo7) >>>>>>>>>>>>>>>>>

- (void)startAutoCellHeightWithCellClasses:(NSArray<class> *)cellClassArray contentViewWidth:(CGFloat)contentViewWidth; // cellClassArray 为所有cell的类组成的数组，详细用法见demo7

这句class报错，  Cannot find protocol ldeclaration for 'class",
是我的Xcode版本太低么？6.3

**Comment by gsdios** [comment]
7以下的xcode上 把 <class> _nonnull 之类的去掉就可以了

**Comment by weixianlove** [comment]
可以用了，谢谢
