### ISSUE TITLE
里面使用了私有API--> UITableViewCellContentView   苹果审核通不过咋办

### ISSUE THREAD

**Issue by G7b9** [gsdios/SDAutoLayout#195]

**Comment by gsdios** [comment]
是因为这个原因拒掉的？邮件内容贴出来或者发我我看下

**Comment by iamgod588** [comment]
我也被拒了  请问怎么解决呢

**Comment by G7b9** [comment]
后面我全局搜了一下，发现其实只是引用了这个第三方的头文件，里面并没有使用这个第三方。
我用pod把他移除了。

你项目里面一直用这个吗？
只能移除了，坐等作者更新。换个第三方或者用自己的方法，先通过审核吧。

**Comment by G7b9** [comment]
下面这个是那一次被拒的回信

Guideline 1.2 - Safety - User Generated Content


Your app enables the display of user-generated content but does not have the proper precautions in place.

Next Steps

To resolve this issue, please revise your app to implement all of the following precautions:

- Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
- A method for filtering objectionable content
- A mechanism for users to flag objectionable content
- A mechanism for users to block abusive users
- The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

Request a phone call from App Review

At your request, we can arrange for an Apple Representative to call you within the next three business days to discuss your App Review issue. Our representative will be able to discuss the issue in English or Chinese.

To request a call and ensure we have accurate contact information, reply directly to this message with a contact name and direct phone number to reach you.

申请应用审核团队致电联系

如果您有需要，我们将根据您的要求在三个工作日内安排一位精通中文的苹果公司代表致电与您联系，讨论您的应用审核结果。
为了确保我们有正确的联系资料，请回复这封邮件并提供您的姓名与电话号码。

申請應用審核團隊致電聯繫

如果您有需要，我們將根據您的要求在三個工作日內安排一位精通中文的蘋果公司代表致電與您聯繫，討論您的應用審核結果。
為了確保我們有正確的聯繫資料，請回覆這封郵件並提供您的姓名與電話號碼。

Guideline 2.5.1 - Performance - Software Requirements


Your app also still uses or references the following non-public APIs:

_UIRotatingAlertController, UIAlertButton, UIInputSetHostView, UIRemoteKeyboardWindow, UITableViewCellContentView, WKActionSheet

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

To resolve this issue, please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your app being flagged in future submissions.

Additionally, if you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

For information on the "nm" tool, please review the "nm tool" Xcode manual page.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

这些附件可能会显示可能令人反感的内容，如裸露、色情和亵渎内容。
* 		Screenshot-0529-121144.png
* 		Screenshot-0529-121141.png

**Comment by gsdios** [comment]
只有极少部分用户有反馈，不过已经做相应处理了，6月27更新了代码
