### ISSUE TITLE
你好，我这里遇到个SDAutoLayout失效问题

### ISSUE THREAD

**Issue by GoodApple7** [gsdios/SDAutoLayout#198]
你好 我在项目里集成SDAUtoLayout之后 今天早上过来打开项目 约束全部失效了

**Comment by gsdios** [comment]
检查下是不是你新添加了某些类库用到了对load方法有误操作导致

**Comment by GoodApple7** [comment]
在一个.m文件里同时使用了iOS原生布局和SD
