### ISSUE TITLE
关于UITextView动态录入实现cell的高度自适应问题

### ISSUE THREAD

**Issue by ZT-xiaobai** [gsdios/SDAutoLayout#201]
您好 我们项目现在有个需求是 cell里面有个UITextview,需要用户在录入文字信息的时候cell的高度动态自动扩展(自适应),请问这个要怎么实现?

**Comment by gsdios** [comment]
这个和自动布局无关，主要是一个刷新机制的问题，你先尝试不用自动布局时候如何实现，实现之后可以把原来的非自动布局换成自动布局

**Comment by ZT-xiaobai** [comment]
OK,多谢
