### ISSUE TITLE
删除section 后面的section高度就计算不正确了

### ISSUE THREAD

**Issue by gaoyz** [gsdios/SDAutoLayout#203]
删除Cell没问题，就是删除section时就出问题了，每个section里就一个Cell，Cell的高度都是动态变化的，您方便的时候可以试下看？

**Comment by gsdios** [comment]
sd尚未添加删除section时的高度缓存自动清理功能，你可以先自己调用缓存清理方法[yourTableView.cellAutoHeightManager clearHeightCache]
