### ISSUE TITLE
IOS7.1下横屏时仍然存在问题

### ISSUE THREAD

**Issue by fengyunjue** [gsdios/SDAutoLayout#21]
1.DemoVC1先竖屏在横屏,有内存泄露;
2.DemoVC3横屏黄色的View位置不对
![img_4435](https://cloud.githubusercontent.com/assets/6801297/12409381/70de9cba-bea4-11e5-801b-0ab38645009f.PNG)
3.DemoVC5,DemoVC7,DemoVC8和DemoVC9横屏cell的高度计算不对
![img_4436](https://cloud.githubusercontent.com/assets/6801297/12409382/75751826-bea4-11e5-9244-b99cb68880fa.PNG)
![img_4437](https://cloud.githubusercontent.com/assets/6801297/12409384/75c45fb2-bea4-11e5-9a76-2e7bf1828b9e.PNG)

**Comment by gsdios** [comment]
这些问题已经解决了，晚上 更新代码到github

**Comment by fengyunjue** [comment]
期待中....

**Comment by gsdios** [comment]
请下载 最新代码测试下
