### ISSUE TITLE
使用tableview 的deleteRowsAtIndexPaths 方法 闪退

### ISSUE THREAD

**Issue by OnVo** [gsdios/SDAutoLayout#217]
断点最后停留处
SDCellAutoHeightManager文件的
- (NSString *)cacheKeyForIndexPath:(NSIndexPath *)indexPath
{
    return [NSString stringWithFormat:@"%ld-%ld", (long)indexPath.section, (long)indexPath.row];
}

**Comment by beiguancyc** [comment]
同样在deleteRowsAtIndexPaths 时闪退

**Comment by gsdios** [comment]
先参照下demo5.demo5点击cell时会删除对应cell。
