### ISSUE TITLE
优酷视频里面讲的frame缓存是什么意思？

### ISSUE THREAD

**Issue by xuchuandong** [gsdios/SDAutoLayout#218]
您好，之前一直用您的库，但用的并不好，我今天看了您优酷视频，感觉收益很多，但是视频最后部分的frame缓存没有看懂，不知道是什么意思，可否讲解一下，感激不尽！

**Comment by gsdios** [comment]
frame缓存就是把使用自动布局的一些控件计算好的frame缓存下来，如果控件的数据或者约束没有发生变化，下次就直接使用缓存下来的frame而不必每次都计算frame
