### ISSUE TITLE
基于中心或者右边的可变宽度的自动布局体验很差！

### ISSUE THREAD

**Issue by colin-liu** [gsdios/SDAutoLayout#222]
我尝试将按钮基于view中心线对齐，然后使用`setupAutoWidthWithRightView:rightMargin:`方法根据按钮的titleLabel自动布局，运行后不会崩溃，但是就卡在页面，什么都动不了。

基于view右侧对齐的效果同样。
望给出解决方案！谢谢！

**Comment by gsdios** [comment]
我验证了一下没有发现问题，你先参照demo1看下。如果还是有问题把你的代码发我邮箱gsdios@126.com看下
