### ISSUE TITLE
刷新cell  提示数组越界

### ISSUE THREAD

**Issue by iamgod588** [gsdios/SDAutoLayout#223]
为了让一张图片时候图片能够自适应（服务器没给我图片size），我在图片加载完后返回图片高度通知tableview重新reload那个cell，但是[UITableView(SDAutoTableViewCellHeight) sd_reloadRowsAtIndexPaths:withRowAnimation:] 提示[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'，表示理解不能，而且有时候界面上回多画出一个cell，数据源并没有增加，大神看到了能加个qq帮我看看问题嘛 642261164

**Comment by gsdios** [comment]
这里还是你代码逻辑的问题，先自查一下
