### ISSUE TITLE
UITextView如何高度自适应? 包括富文本.

### ISSUE THREAD

**Issue by JoeZhangXQ** [gsdios/SDAutoLayout#228]

**Comment by JiekangLiao** [comment]
/**
 *  自适应label高度，根据正文内容多少,动态确定正文content的frame
 *
 *  @param fontNumber 字体大小
 *  @param width      文本视图宽度
 *
 *  @return 文本尺寸

_[](url)_


 */
+(CGRect)autoResetFrameWithFontNumber:(CGFloat)fontNumber andFrame:(CGRect)frame andText:(NSString *)text minHeight:(CGFloat)minHeight{
    // 宽度W
    CGFloat contentW = frame.size.width;
    // label的字体 HelveticaNeue  Courier
    UIFont *fnt = [UIFont fontWithName:@"HelveticaNeue" size:fontNumber];
    // iOS7中用以下方法替代过时的iOS6中的sizeWithFont:constrainedToSize:lineBreakMode:方法
    CGRect tmpRect = [text boundingRectWithSize:CGSizeMake(contentW, 1000) options:NSStringDrawingUsesLineFragmentOrigin attributes:[NSDictionary dictionaryWithObjectsAndKeys:fnt,NSFontAttributeName, nil] context:nil];
    // 高度H
    CGFloat contentH = tmpRect.size.height;
    if (contentH<minHeight && minHeight!=0) {
        contentH = minHeight;
    }
    return CGRectMake(frame.origin.x, frame.origin.y, contentW,contentH+2*CELLGAP);
}__

**Comment by JoeZhangXQ** [comment]
@JiekangLiao  谢谢  我指的是用SDLayout来做

**Comment by JiekangLiao** [comment]
我也没去了解，我用纯代码的

**Comment by gsdios** [comment]
看头文件api

/** 是否是attributedString */
@property (nonatomic) BOOL isAttributedContent;
