### ISSUE TITLE
适配iOS 11 safe Area

### ISSUE THREAD

**Issue by MrWilsonXu** [gsdios/SDAutoLayout#230]
作者需要尽快更新来适配iOS 11，已经出现许多布局问题

**Comment by AssassinrKiller** [comment]
ios 11 运行直接断在 sd_layoutSubviews  很难找到 布局问题啊

**Comment by gsdios** [comment]
ok，我近两天看下。

**Comment by gsdios** [comment]
你遇到具体什么问题可以加QQ群519489682然后找到我反馈一下。
