### ISSUE TITLE
如果是最后一个试图没有加宽高的话 自动计算会有问题，应该也有自适应根据文字或者图片

### ISSUE THREAD

**Issue by JianmingFu** [gsdios/SDAutoLayout#246]

**Comment by gsdios** [comment]
描述太笼统，再补充一下。

**Comment by JianmingFu** [comment]
就是从上往下开始布局，至最后一个试图，比如说一个button，然后调用提供的方法，如果button本身没有设置宽高的话计算会有点问题，加上就好了，这是我调试遇到的。我觉得应该会例如根据lable的文字，或者button的title，图片 自动适应

**Comment by JianmingFu** [comment]
不好意思是- 视图
