### ISSUE TITLE
- (void)sd_reloadRowsAtIndexPaths:(NSArray *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation

### ISSUE THREAD

**Issue by topjx** [gsdios/SDAutoLayout#261]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert row 0 into section 2, but there are only 2 sections after the update'

这是什么鬼？

**Comment by topjx** [comment]
@gsdios

**Comment by gsdios** [comment]
SDAutoLayout在运行时交换了reloadRowsAtIndexPaths方法，当你调用reloadRowsAtIndexPaths方法时候就会走到sd_reloadRowsAtIndexPaths:这里，但往往这个错误和sd美颜关系，还是需要你检查下你在什么地方调用reloadRowsAtIndexPaths:方法

**Comment by topjx** [comment]
嗯嗯

**Comment by JiekangLiao** [comment]
数组越界
