### ISSUE TITLE
UIScrollView 滑动卡顿

### ISSUE THREAD

**Issue by wooden1985** [gsdios/SDAutoLayout#282]
UIScrollView contentsize 内容很多的时候滑动卡顿 跟使用了 setupAutoContentSizeWithBottomView 有关系吗？

**Comment by wooden1985** [comment]
UIScrollView里面摆放布局复杂的界面滑动就会卡，把view做成一个headview放在uitableview里面滑动就不卡

**Comment by SongLog** [comment]
确实是这样,但是为什么呢.在scrollview里面就会卡顿.

**Comment by SongLog** [comment]
> UIScrollView里面摆放布局复杂的界面滑动就会卡，把view做成一个headview放在uitableview里面滑动就不卡

确实是这样,但是为什么呢.在scrollview里面就会卡顿.

**Comment by gsdios** [comment]
scrollview滚动时候会不断触发layoutsubviews方法回调导致频繁布局约束计算，可以参考demo对于scrollview的处理；或者你可以自己仿照tableview的做法加一层wrapperview来管理所有子view也可以解决这个问题。

**Comment by Yaanco** [comment]
> scrollview滚动时候会不断触发layoutsubviews方法回调导致频繁布局约束计算，可以参考demo对于scrollview的处理；或者你可以自己仿照tableview的做法加一层wrapperview来管理所有子view也可以解决这个问题。

请问你说的是demo12吗，添加一个flowItemContentView？希望大佬看到可以回复下，现在scroll卡顿比较明显，谢谢啦
