### ISSUE TITLE
使用.didFinishAutoLayoutBlock获取布局完成后的View的frame

### ISSUE THREAD

**Issue by beydeng** [gsdios/SDAutoLayout#287]
当我调用.didFinishAutoLayoutBlock之后 给view添加layer之后，在我没有改变view的frame时，但是重复收到了这个回调，倒置重复添加layer的问题。
请问下，这样的问题是我使用的错误导致的么？

**Comment by gsdios** [comment]
didFinishAutoLayoutBlock在每次根据约束计算完frame之后会回调，根据不同的约束组合以及约束的复杂程度可能会产生不止一回调。
