### ISSUE TITLE
DemoVC0没有停止定时器

### ISSUE THREAD

**Issue by RayTao** [gsdios/SDAutoLayout#29]
应添加以下代码
- (void)dealloc
{
    [_timer invalidate];
    _timer = nil;
}

**Comment by huangxianhui001** [comment]
定时器会持有这个控制器,这时候控制器的dealloc方法根本就不会走,也就谈不上在dealloc里面停止定时器了,应该在viewwilldisappear的时候停止定时器,

**Comment by gsdios** [comment]
好的，已经修复，感谢关注与支持！
