### ISSUE TITLE
崩溃，在[self.rightTableView cellHeightForIndexPath: model: keyPath: cellClass: contentViewWidth:]崩溃

### ISSUE THREAD

**Issue by yangxiutao** [gsdios/SDAutoLayout#291]
在[self.rightTableView cellHeightForIndexPath:indexPath model:model keyPath:@"model" cellClass:[SDProvinceConvenienceHomeRightCell class] contentViewWidth:(CGRectGetWidth(self.view.frame) - 30)]中崩溃
![image](https://user-images.githubusercontent.com/14293378/44015609-50a995a6-9f04-11e8-810c-67ffc639badb.png)

**Comment by Just013** [comment]
> 在[self.rightTableView cellHeightForIndexPath:indexPath model:model keyPath:@"model" cellClass:[SDProvinceConvenienceHomeRightCell class] contentViewWidth:(CGRectGetWidth(self.view.frame) - 30)]中崩溃
> ![image](https://user-images.githubusercontent.com/14293378/44015609-50a995a6-9f04-11e8-810c-67ffc639badb.png)

你看一下这个方法的注释，kvc对应cell里模型的名称。 不一定是作者的model，你写的是什么这里才是什么。

**Comment by earlyfly** [comment]
请问问题解决了吗？当tableview是分组的时候，一个model作为一个section（包含多个row）的数据源的情况时，代码真会崩溃在UITableView+SDAutoTableViewCellHeight.m中的267行代码：[self.modelCell setValue:model forKey:keyPath];

使用的SDAutoLayout的版本为2.2.1

使用[self cellHeightForIndexPath:indexPath cellContentViewWidth:[UIScreen mainScreen].bounds.size.width];是没问题的，但是作者说这个方法在cell数超过100时会影响性能。求解
