### ISSUE TITLE
你好、请问在cell中嵌套了tableview的话支持吗？

### ISSUE THREAD

**Issue by hongdong** [gsdios/SDAutoLayout#3]
你好、请问在cell中嵌套了tableview的话支持吗？

**Comment by gsdios** [comment]
具体怎样嵌套呢，你项目的具体要求是什么，为什么会有这样的实现方案呢？

**Comment by hongdong** [comment]
类似微信朋友圈那样的需求、我实现起来是cell中嵌套一个留言评论的table
