### ISSUE TITLE
SD的一个bug,同一个indexPath会出现两个cell,不知道大家有没有遇见

### ISSUE THREAD

**Issue by baiyidjp** [gsdios/SDAutoLayout#302]
公司的项目,前人用的SD的布局,我不使用,但是每次cell进行单独indexpath的刷新的后,都会重新创建一个新的cell.具体是

BYCell *userInfoCell = [tableView dequeueReusableCellWithIdentifier:@"BYCellID"];

这里拿到的cell不一样,indexPath.row = 0 的 也就是只有一个cell

查看层级结构,发现的确是存在两个cell,一个是reload之前的一个是reload之后的.

不知道大家有没有遇见

**Comment by CaiChenghan** [comment]
楼主怎么解决的？我也遇到了同样的情况

**Comment by CaiChenghan** [comment]
我的是cell的创建，会执行2次

**Comment by baiyidjp** [comment]
> 我的是cell的创建，会执行2次

忘记了这是什么东西了。都2年了。。
cell的创建会执行两次，肯定是刷新了2次呗 。
