### ISSUE TITLE
作者你好，之前用这个库好好的，现在iOS12 使用遇到问题

### ISSUE THREAD

**Issue by muyang00** [gsdios/SDAutoLayout#317]
<img width="1805" alt="屏幕快照 2019-05-18 上午10 46 08" src="https://user-images.githubusercontent.com/16149500/57963680-7f397400-795a-11e9-9e9a-aaa04a93836d.png">
cell上东西莫名消失不见， 布局问题应该没问题

**Comment by bolee** [comment]
设置frame之后，调用`setSingleLineAutoResizeWithMaxWidth`，这个框架有问题，根本没法符合需求。

**Comment by liujunliuhong** [comment]
以前还用这个库，感觉还挺不错的，不过现在已经不用了

**Comment by gsdios** [comment]
demo在iOS12上可以正常运行的。你有什么问题吗可以把代码看下。
