### ISSUE TITLE
UILabel类设置约束失效，其他类没问题，排查了很久都没找到问题在哪

### ISSUE THREAD

**Issue by JanWirt** [gsdios/SDAutoLayout#320]

**Comment by JanWirt** [comment]
测试发现，必须设置 setSingleLineAutoResizeWithMaxWidth 布局才会生效，多行依然失效，不知道跟什么冲突了

**Comment by JanWirt** [comment]
UILabel *test = [[UILabel alloc]init];
    test.backgroundColor = KPRandomColor;
    [self.view addSubview:test];
    
    test.sd_layout.leftSpaceToView(self.view, 30).topSpaceToView(self.view, 100).widthIs(100).heightIs(30);

我这样写，视图上完全找不到控件。

**Comment by JanWirt** [comment]
找到问题了，搜了UILabel分类，有个文件用了runtime修改了width，其实刚开始就看到了这个文件，记得当时注释了还是不行，现在还是这里的问题，果然还是要一点点排查问题。

**Comment by MimiOuO** [comment]
老哥 同样的问题，谢谢Thanks♪(･ω･)ﾉ

**Comment by bolee** [comment]
如果只有一个控件时候要调用这个setSingleLineAutoResizeWithMaxWidth才能生效

**Comment by wxzwork** [comment]
现在发现也有这个问题 我约束的label的上、左、右间距，然后是高度自适应，发现左右的约束不生效呢，有时候文字会显示不全，项目中没有相关的label分类修改了label的宽度，不懂还会有什么原因造成
