### ISSUE TITLE
大佬,咱这库还维护吗

### ISSUE THREAD

**Issue by GrapeFruitJun** [gsdios/SDAutoLayout#324]

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by liujunliuhong** [comment]
之前还在用这个库，不过现在已经不用了，个人觉得Hook LayoutSubViews方法会存在很多问题

**Comment by gsdios** [comment]
一直维护呀，有什么问题吗？
