### ISSUE TITLE
关于SDAutoLayout使用了黑魔法替换了layoutSubview的问题

### ISSUE THREAD

**Issue by zhangzhibinhi** [gsdios/SDAutoLayout#325]
SDAutoLayout在View的load方法中通过method_exchangeImplementations替换了layoutSubviews方法
`method_exchangeImplementations(originalMethod, myMethod);`
然而最近的暗黑模式适配我也需要method_exchangeImplementations去替换layoutSubviews方法，结果就报错了，报错的地方，作者写了这么一句
`// 如果程序崩溃在这行代码说明是你的view在执行“layoutSubvies”方法时出了问题而不是在此自动布局库内部出现了问题，请检查你的“layoutSubvies”方法`
我就想问，有什么解决办法没有？

**Comment by chenjiangui** [comment]
你替换的方法有问题 我三重替换没问题. 按照替换顺序执行

**Comment by gsdios** [comment]
// 如果程序崩溃在这行代码说明是你的view在执行“layoutSubvies”方法时出了问题而不是在此自动布局库内部出现了问题，请检查你的“layoutSubvies”方法
