### ISSUE TITLE
技术交流

### ISSUE THREAD

**Issue by netyouli** [gsdios/SDAutoLayout#33]
你这是基于frame布局我写了一款基于autolayout布局
WHC_AutoLayoutKit：https://github.com/netyouli/WHC_AutoLayoutExample
WHC_AutoLayoutKit设计思想借鉴android相对布局和线性布局(垂直和横向)
高度和宽度可按容器权重weight自动拉伸(一排很多视图时或者垂直方向很多视图时)

**Comment by gsdios** [comment]
嗯，看到了，很不错的。
