### ISSUE TITLE
demoVC9 部分优化

### ISSUE THREAD

**Issue by rayonchen** [gsdios/SDAutoLayout#35]
demoVC9 性能优化----在UITableViewDataSource中 不进行数据绑定， 在cell出现之前就会运行的方法 - (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath 进行数据绑定
cell内容图片为3时，展示为一行
在- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath 中布局cell高度时，有个小建议

**Comment by gsdios** [comment]
感谢提供建议，可以加入下qq群497140713 详细说下
