### ISSUE TITLE
如果是UIViewController里加一个UITableView，如何来做？

### ISSUE THREAD

**Issue by realcarlos** [gsdios/SDAutoLayout#37]
目前的Demo都是UITableViewController ，然后调用
return [self cellHeightForIndexPath:indexPath cellContentViewWidth:[UIScreen mainScreen].bounds.size.width];

如果是UIViewController里加一个UITableView，如何来做？

**Comment by realcarlos** [comment]
好像知道了

**Comment by strivingboy** [comment]
同 realcarlos, 这个问题有解决么？

**Comment by gsdios** [comment]
看头文件，有tableview的方法，也有tableviewController的方法，也有NSObject的方法
