### ISSUE TITLE
这个和Masonry有什么异同

### ISSUE THREAD

**Issue by BrightBeacon** [gsdios/SDAutoLayout#4]

**Comment by gsdios** [comment]
1.代码更简洁，方法语义更直观，可以更快布局
2.性能方面和masonry相当，某些情况下性能还要优于masonry

**Comment by BrightBeacon** [comment]
感谢回复，刚从autoSizing转换过来，正想办法快速上手，多谢你封装的这个框架。

**Comment by zuojx1013** [comment]
你好，在我使用一个tableview使用两个cell的时候就会出现问题，不知道是否支持多个cell？

**Comment by gsdios** [comment]
目前还不支持多cell，如果有这个需求的开发者较多的话可以考虑近期添加相关功能。

**Comment by wangbiye** [comment]
我需要多种cell类型的

**Comment by gsdios** [comment]
好的，明天实现下这个功能

**Comment by wangbiye** [comment]
太性了,说搞分分钟就搞了

**Comment by wangbiye** [comment]
我微博上问过一个问题, 就是两个并排的label, 左边的是title,根据不同的title调整宽度,然后剩下的宽度就给右边的message label,我用autolayout的时候就是设置左边的抗拉伸和抗压缩,如果用这个库是什么样的思路呢

**Comment by gsdios** [comment]
你看下 demo5 里面有这种情况，单行文字宽度自适应，然后他的后边加一个标签之类的控件。

**Comment by wangbiye** [comment]
看了,Perfect 等你的多种cell支持做好我就用到项目里去

**Comment by gsdios** [comment]
加入 SDAutoLayout交流群了吗，没有的话加入下（QQ群：497140713），我把实现多cell的最新代码给你测试下，有什么建议可以提下

**Comment by gsdios** [comment]
SDAutoLayout 现已完成对多cell的支持，具体例子请查看demo7

**Comment by wangbiye** [comment]
这就下载瞅瞅

**Comment by gsdios** [comment]
SDAutoLayout的cell高度自适应完成进一步升级：一行代码（一步设置）搞定tableview的cell高度自适应,同时适用于单cell和多cell

**Comment by nanayashiki1215** [comment]
厉害！！看来可以抛掉Masonry了~~

**Comment by anyuhao** [comment]
Masonry 是 autoLayout
这个只是frame的 layout

**Comment by gsdios** [comment]
所有自动布局布局操作最终都是对frame的操作

**Comment by cabinshow** [comment]
请问一个项目里，SDAutoLayout 和 Masonry不能共存嘛？
导入 Masonry 之后，为什么之前 SDAutoLayot 布局的界面都失效了？
请问知道原因吗，怎么解决？

**Comment by gsdios** [comment]
SDAutoLayout的QQ群497140713，可以加入反馈下你的问题

**Comment by shenyuan000** [comment]
SDAutoLayout 和 Masonry不能共存 是怎么回事 有解决的方法吗
