### ISSUE TITLE
能不能自动设置图片的大小？

### ISSUE THREAD

**Issue by ghysrc** [gsdios/SDAutoLayout#42]
今天刚开始用，确实不错，好评一个。
但发现布局图片的时候，必须要明确的指定图片的宽高才能正确显示图片，感觉这样挺麻烦的。
因为之前一直在用Masonry，只要它确定了 imageView 的位置，就会自动按图片的大小显示出来，而不用人为的去设置死的数值。这样感觉是很方便的，UI 那边切出来的图都是合适的大小了，本身就不需要再重新给值。
如果你的框架里本身就有这样的功能那最好，示例一下就好了；没有的话希望可以添加。
谢谢。

**Comment by gsdios** [comment]
你这里说的情况 是 本地的ui素材图片吧。

**Comment by gsdios** [comment]
可以加入 SDAutoLayoutQQ群：497140713  一起交流下
