### ISSUE TITLE
leftEqualToView,topEqualToView等xxEqualToView的方法少了边距的设置

### ISSUE THREAD

**Issue by huangxianhui001** [gsdios/SDAutoLayout#44]
如果我有这种需求:
view0,view1上下两行排列,view1需要对view0的左边偏移一个距离,这时候,leftEqualToView没法满足这个要求,在你的demo5里,我试着用xIs方法来设置图片_view3的左边距离内容label(_view2)偏移10,如下代码:
 _view3.sd_layout
    .topSpaceToView(_view2, 10)
    .xIs(_view2.left + 10)
    .widthRatioToView(_view2, 0.7);
但是查看了你的left方法,仅仅是返回了fram的原点横坐标,这时候横坐标明显是0,所以图片只是显示在了cell左边沿10的位置.
然后有这种需求时,该怎么实现?

**Comment by gsdios** [comment]
下个版本 会加入 偏移量
