### ISSUE TITLE
Cell 的自适应

### ISSUE THREAD

**Issue by YueLiXing** [gsdios/SDAutoLayout#46]
/* model 为模型实例， keyPath 为 model 的属性名，通过 kvc 统一赋值接口 */
return [self.tableView cellHeightForIndexPath:indexPath model:self.modelsArray[indexPath.row] keyPath:@"model"];

在实际应用中，可能是通过一个方法，给cell传递很多参数，而这些参数封装在一个Model里面的话有时并不合适，能否添加一个能通过方法赋多个值的途径?

**Comment by gsdios** [comment]
目前有一个不需要传值的方法，随后会添加一个 block 回调方法 ，你可以在block里面给cell设置任何数据
