### ISSUE TITLE
如何设置子视图在父视图上面自适应居中

### ISSUE THREAD

**Issue by zh20102618** [gsdios/SDAutoLayout#47]
设置子视图居中只能设置固定的值widthIs和heightIs，在父视图自适应的时候，子视图大小不变时就显示不居中了，不能参照父视图直接设置居中吗？centerXEqualToView和centerYEqualToView要参照兄弟视图才行，如果没有兄弟视图，第一个添加的字视图如何设置居中？

**Comment by CoderNevinZ** [comment]
那个view 可以是 你的superview

**Comment by gsdios** [comment]
centerXEqualToView和centerYEqualToView 可以参照父view的
