### ISSUE TITLE
demoVC9 有个小问题

### ISSUE THREAD

**Issue by Mrzhang007** [gsdios/SDAutoLayout#48]
就是点击全文，收起的时候会有一个阴影效果。

**Comment by ryanypm** [comment]
[weakSelf.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationFade];
改成
[weakSelf.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];
