### ISSUE TITLE
用storyboard 布局，静态的tablecell怎么设置自适应高度呢？

### ISSUE THREAD

**Issue by liu521227** [gsdios/SDAutoLayout#51]

**Comment by gsdios** [comment]
在 cell的 aweakFromXib 中 调用 setupAutoHeightWithBottomView:bottomMargin 就可以了

**Comment by liu521227** [comment]
没有创建自定义cell，我是直接在controller里面把cell拉成属性，这中情况下能自适应高度不？还是说必须要创建自定义cell

**Comment by gsdios** [comment]
可以

**Comment by shuiliang** [comment]
我也是 storyboard 的静态代码,但是我没有用到 model, 不知道 heightForRowAtIndexPath里面怎么写,请朋友指教,谢谢!
