### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by CoderNevinZ** [gsdios/SDAutoLayout#55]
现有一个三级列表的需求，我试图在自定义的cell中添加一个TableView,然后在cell中用SD添加布局。可是运行之后就直接crash到这里的cacheKey，如下
- (NSNumber *)heightCacheForIndexPath:(NSIndexPath *)indexPath
{
    NSString *cacheKey = [NSString stringWithFormat:@"%ld%ld", (long)indexPath.section, (long)indexPath.row];
    return (NSNumber *)[_cacheDictionary objectForKey:cacheKey];
}

是什么原因，我该怎么解决

**Comment by gsdios** [comment]
- (NSNumber *)heightCacheForIndexPath:(NSIndexPath *)indexPath
{
    /*
     如果程序卡在了这里很可能是由于你用了“dequeueReusableCellWithIdentifier:forIndexPath:”方法来重用cell，换成““dequeueReusableCellWithIdentifier:”（不带IndexPath）方法即可解决
     */
    NSString *cacheKey = [NSString stringWithFormat:@"%ld%ld", (long)indexPath.section, (long)indexPath.row];
    return (NSNumber *)[_cacheDictionary objectForKey:cacheKey];
}

**Comment by CoderNevinZ** [comment]
嗯，后来去掉了折合的功能，就没事了
