### ISSUE TITLE
我用Xib创建的cell，怎么修改cell里面内容的约束？

### ISSUE THREAD

**Issue by wings0728** [gsdios/SDAutoLayout#56]
我想动态修改他的高度，我是这么写的：
 
        _nameLabel.sd_layout.heightIs(_iconView.height);
               

结果崩溃了：

reason: '-[UILabel sd_layout]: unrecognized selector sent to instance 0x7fb4334f8880'

我现在尝试不用xib，但是也奔溃，完全不知道问题出在哪里

        UIImageView *iconView = [[UIImageView alloc] init];
        [self.contentView addSubview:iconView];
        _iconView = iconView;
        
        iconView.sd_layout
        .topSpaceToView(self.contentView, 5)
        .leftSpaceToView(self.contentView, 5)
        .bottomSpaceToView(self.contentView, 5)
        .widthEqualToHeight();
        
错误信息：-[UIImageView sd_layout]: unrecognized selector sent to instance 0x7fa7b5c7e9a0

**Comment by gsdios** [comment]
clear下工程再试试，加入 SDAutoLayout qq交流群（497140713）然后联系下我反馈下你的问题
