### ISSUE TITLE
关于视图顶部及底部的适配问题

### ISSUE THREAD

**Issue by leeZePeng** [gsdios/SDAutoLayout#58]
masonry 里边有mas_topLayoutGuide;
mas_bottomLayoutGuide;
mas_topLayoutGuideTop;
mas_topLayoutGuideBottom;
mas_bottomLayoutGuideTop;
mas_bottomLayoutGuideBottom;

SDAutolayout中怎么去实现这个呢？

**Comment by gsdios** [comment]
具体要实现什么样的功能呢？

**Comment by leeZePeng** [comment]
在导航或分栏控制器中translucent属性的默认值为YES，并且当前的ViewController的高度会是整个屏幕的高度，不更改translucent属性的同时确保视图不被这些Bar覆盖
