### ISSUE TITLE
功能修改

### ISSUE THREAD

**Issue by YiQieSuiYuan** [gsdios/SDAutoLayout#6]
// 修改
@property (nonatomic, copy, readonly) WidthHeightEqualToView widthRatioToView;
@property (nonatomic, copy, readonly) WidthHeightEqualToView heightRatioToView;

// 新加
@property (nonatomic, copy, readonly) WidthHeightEqualToView widthRatioToViewWidth;
@property (nonatomic, copy, readonly) WidthHeightEqualToView widthRatioToViewHeight;
@property (nonatomic, copy, readonly) WidthHeightEqualToView heightRatioToViewWidth;
@property (nonatomic, copy, readonly) WidthHeightEqualToView heightRatioToViewHeight;

库中功能十分好用，如果能完善下面功能就更加完美了
（1）widthRatioToView heightRatioToView都是基于宽和宽 高和高的比例，缺少高和宽的比例约束
（2）没有等宽等高的约束

**Comment by gsdios** [comment]
已经有了，你可以下载最新代码看下
