### ISSUE TITLE
父view中的动态属性autoLayoutModelsArray中的Model什么时候移除呢？

### ISSUE THREAD

**Issue by february29** [gsdios/SDAutoLayout#60]
1.childView调用sd_layout态生成一个model动态添加到self。
2.同时这个model也会添加到父view(parentView)的autoLayoutModelsArray当中去。
3.如果我以后调用childView removeFromSuperView以后 那么parentView当中的modle会从autoLayoutModelsArray中移除么？
4.如果不移除 parentView 在调用layoutsubviews时是否还会遍历autoLayoutModelsArray找到对应model实现布局？此时model中的needsAutoResizeView会是什么呢？
5.如果移除是怎样实现的呢？sd_clearAutoLayoutSettings？还是其他方法？能具体解释一下么？

**Comment by gsdios** [comment]
一般会在父view销毁时删除所有的子view的约束模型。约束模型对needsAutoResizeView都是weak弱引用，如果一个view执行了removeFromSuperView方法，约束模型的needsAutoResizeView属性会自动置空为nil。另外也可以手动调用sd_clearAutoLayoutSettings彻底清除自身的约束。
