### ISSUE TITLE
关于tableviewcell高度缓存的一点小建议

### ISSUE THREAD

**Issue by immrss** [gsdios/SDAutoLayout#64]
如果用一个MutableArray来存储行高，处理tableview更新时会不会更方便。写了个小demo，没有用到methodswizzling，子类化了一个uitableview

`@interface TableView ()
@property (nonatomic, strong) NSMutableArray *heightCacheArray;
@end

@implementation TableView

static const CGFloat kPlaceholderCellHeight = -1.0;

- (instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style {
    self = [super initWithFrame:frame style:style];
    if (self) {
        self.heightCacheArray = [NSMutableArray new];
    }
    return self;
}

- (void)reloadData {
    [self.heightCacheArray removeAllObjects];
    [super reloadData];
}

- (void)reloadRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation {
    NSMutableIndexSet *indexSet = [NSMutableIndexSet new];
    NSMutableArray *array = [NSMutableArray array];
    for (NSIndexPath *indexPath in indexPaths) {
        [indexSet addIndex:indexPath.row];
        [array addObject:@(kPlaceholderCellHeight)];
    }
    [self.heightCacheArray replaceObjectsAtIndexes:indexSet withObjects:array];
    [super reloadRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}

- (void)insertRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation {
    NSMutableIndexSet *indexSet = [NSMutableIndexSet new];
    NSMutableArray *array = [NSMutableArray array];
    for (NSIndexPath *indexPath in indexPaths) {
        [indexSet addIndex:indexPath.row];
        [array addObject:@(kPlaceholderCellHeight)];
    }
    [self.heightCacheArray insertObjects:array atIndexes:indexSet];
    [super insertRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}

- (void)deleteRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation {
    NSMutableIndexSet *indexSet = [NSMutableIndexSet new];
    for (NSIndexPath *indexPath in indexPaths) {
        [indexSet addIndex:indexPath.row];
    }
    [self.heightCacheArray removeObjectsAtIndexes:indexSet];
    [super deleteRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}

//返回indexPath对应的cell行高，model为该行数据。
- (CGFloat)cellHeightWithModel:(id<CellModelCalculate>)model forIndexPath:(NSIndexPath *)indexPath {
    if (indexPath.row >= self.heightCacheArray.count) {
        CGFloat height = [model calculateHeight];
        [self.heightCacheArray addObject:@(height)];
        return height;
    }
    NSNumber *number = self.heightCacheArray[indexPath.row];
    CGFloat height = (CGFloat)[number floatValue];
    if (height <= 0) {
        CGFloat newHeight = [model calculateHeight];
        [self.heightCacheArray replaceObjectAtIndex:indexPath.row withObject:@(newHeight)];
        return newHeight;
    }
    return height;
}

@end`
个人愚见

**Comment by gsdios** [comment]
好的，收到反馈信息，我随后会仔细测试研究下，感谢关注与支持！

**Comment by immrss** [comment]
😄大神给我回复了！！
我的想法是：
tableview在请求行高的时候indexpath顺序肯定是从0到count-1的，第一个indexpath请求时数组是空的，计算对应的高度，并把数据放到数组里，只要判断当前indexpath.row>=数组的count,就计算高度，并追加到数组里，否则就从数组中对应的位置去取缓存，那么tableview第一次请求完所有的indexpath后，数组中就是对应位置的indexpath的数据。deleteRows时，删除对应位置的数据就行，reloaddata时清空数组，insertRows时，在数组对应的位置插入一个（-1），请求这行高度时，发现数组取出来的高度小于0，那计算这个高度，并替换到数组中对应的位置。reloadRows时，同样将数组中对应位置的高度替换成（-1），剩下的和insertRows时一样。

**Comment by gsdios** [comment]
有一个问题是多section，每个section的cell数量又不一定的情况下用数组会不会就不方便了呢
