### ISSUE TITLE
设置控件圆角没反应

### ISSUE THREAD

**Issue by liu521227** [gsdios/SDAutoLayout#69]
如果一个view不用sdautoLayout来自适应布局，用xib布局或者用原生代码来布局，但用sd_cornerRadiusFromWidthRatio、sd_cornerRadius来设置view的圆角，没有效果。。。必须使用sdautoLayout布局的view设置圆角才有效果。。。这个问题能解决不？

**Comment by gsdios** [comment]
这个圆角效果是在sd布局完成后调用的，目前只能供使用SDAutoLayout布局的view来使用
