### ISSUE TITLE
当UILabel使用html标记的属性文本时，改变文本的字体大小，高度无法自适应？？？

### ISSUE THREAD

**Issue by qimuya3** [gsdios/SDAutoLayout#70]
问题代码片段：
    _cookMethod.sd_layout
    .topSpaceToView(_cmImage, 2)
    .rightSpaceToView(wc, 10)
    .leftEqualToView(_cmImage)
    .autoHeightRatio(0);
    
NSAttributedString * attrStr = [[NSAttributedString alloc] initWithData:[model.cookMenuDetail.message dataUsingEncoding:NSUnicodeStringEncoding] options:@{ NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType,NSFontAttributeName : [UIFont boldSystemFontOfSize:18] } documentAttributes:nil error:nil];

_cookMethod.font = [UIFont systemFontOfSize:17];
_cookMethod.attributedText = attrStr;
即使设置了_cookMethod.isAttributedContent = YES;

**Comment by iCoobin** [comment]
我也遇到这个问题，你有解决办法了吗？

**Comment by gsdios** [comment]
可以加入SDAutoLayout qq交流群（497140713）交流下

**Comment by maker997** [comment]
请问这个问题解决了吗

**Comment by qimuya3** [comment]
我自己解决了




| |
hjm
邮箱：qimuya3@163.com
|

Signature is customized by Netease Mail Master

在2018年07月03日 13:11，maker997 写道：

请问这个问题解决了吗
