### ISSUE TITLE
和SDWebImageView和TableViewCell一起使用时有些问题

### ISSUE THREAD

**Issue by mengxianliang** [gsdios/SDAutoLayout#72]
当Cell的ImageView通过SDWebImage加载完成后，ImageView需要实现自动适应下载完成的图片宽高。要实现这个要有一定的延迟时间，在图片加载完成后 sdAutoLayout已经失效了，在改变cell中ImageView的宽高后怎么重新刷新列表，求指导。

**Comment by gsdios** [comment]
图片的尺寸信息应该由服务器返回
