### ISSUE TITLE
今天刚升级，sizeToFit会出问题

### ISSUE THREAD

**Issue by beiguancyc** [gsdios/SDAutoLayout#74]
以前的uilabel写的很正常，先写布局self.lbnextCheckTime.sd_layout.topSpaceToView(self.lbbabyMonthAge,10).leftEqualToView(self.lbbabyName).widthIs(60).heightIs(30);
载入数据后使用sizeToFit
升级到2.0后宽度是60，sizeToFit不起作用

**Comment by chadchentao** [comment]
我也遇到这个问题

**Comment by gsdios** [comment]
label有单行文字自适应方法的，/** 设置单行文本label宽度自适应 */ - (void)setSingleLineAutoResizeWithMaxWidth:(CGFloat)maxWidth;
