### ISSUE TITLE
升级后存在些小问题

### ISSUE THREAD

**Issue by chadchentao** [gsdios/SDAutoLayout#75]
sizeToFit方法失效.
另外使用新版本后,View自定义动画有点慢,CPU的使用率比之前高不少

**Comment by chadchentao** [comment]
麻烦大牛来解决下

**Comment by chadchentao** [comment]
使用之前的版本,加载动画CPU使用率是40%左右,使用最新版后,CPU使用率达90+%

**Comment by gsdios** [comment]
下载最新代码测试下，SDAutoLayout的方法中有专门设置label的宽度自适应方法的，不需要在使用sizeToFit了
