### ISSUE TITLE
如何让一个view的bottom和另一个view的centerY对齐，or一个view的left和另一个view的centerX对齐？

### ISSUE THREAD

**Issue by gaoyangclub** [gsdios/SDAutoLayout#76]
原生的autoLayout和snapKit对齐方式可以实现一个view的某个属性对齐另一个view的其他属性这种方式，在SDAutoLayout中该怎么实现？

**Comment by gsdios** [comment]
SDAutoLayout目前尚无实现此类方法，以后的版本会根据需求程度的大小依次补充完善。
