### ISSUE TITLE
2.0新版本用pop做动画有bug，1.5.3没有

### ISSUE THREAD

**Issue by beiguancyc** [gsdios/SDAutoLayout#78]
用来做按钮缩小动画
loginButton.sd_layout.centerXEqualToView(loginTableview).widthIs(120).heightIs(30).topSpaceToView(loginTableview,-60);
[loginButton addTarget:self action:@selector(scaleToSmall)
   forControlEvents:UIControlEventTouchDown | UIControlEventTouchDragEnter];
- (void)scaleToSmall
{
    POPBasicAnimation *scaleAnimation = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerScaleXY];
    scaleAnimation.toValue = [NSValue valueWithCGSize:CGSizeMake(0.65f, 0.65f)];
    [loginButton.layer pop_addAnimation:scaleAnimation forKey:@"layerScaleSmallAnimation"];
}
1.5.3正常，尺寸变小。
2.0 button尺寸没有变小，button的textlabel变小了。

**Comment by beiguancyc** [comment]
我觉得这应该是1.5.3的bug，2.x似乎算是修正？

**Comment by gsdios** [comment]
可以加入SDAutoLayoutQQ群497140713反馈下你的问题
