### ISSUE TITLE
sd_addSubviews 可以增加判断view不为空

### ISSUE THREAD

**Issue by GanHuaLin** [gsdios/SDAutoLayout#79]
因为自己的一个疏忽， 在 sd_addSubviews 时传入了一个 没有 new 的UIView ,然后就一直报错，找了好半天才找到这个问题。
Ps：因为如果直接用self addSubView, 一般都是new一个add一个，不容易出现没new的情况。
然而使用 sd_addSubviews 我会首先声明好需要用到的View，一个一个new完，最后一次性sd_addSubviews 。就是这样漏了一个没有new。

**Comment by gsdios** [comment]
这个应该是你在封装那个subviews数组参数时候就报错，你只要能把数组传过来，数组里面肯定都不会为空的

**Comment by GanHuaLin** [comment]
self.label1 = [UILabel new];
    self.label1.font = [UIFont systemFontOfSize:12];
    self.label1.textColor = [UIColor darkGrayColor];
    
    self.label2 = [UILabel new];
    self.label2.font = [UIFont systemFontOfSize:12];
    self.label2.textColor = [UIColor darkGrayColor];
    
    self.label3 = [UILabel new];
    self.label3.font = [UIFont systemFontOfSize:12];
    self.label3.textColor = [UIColor darkGrayColor];
    
    [self sd_addSubviews:@[self.label1,self.label2,self.label3,self.label4]];

就是这样，self.label4没有new过被我大意给忘记了，然后在计算Cell高度里就报错

(CGFloat)cellHeightForIndexPath:(NSIndexPath *)indexPath model:(id)model keyPath:(NSString *)keyPath

if (model && keyPath) {
//这句报错： [__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[11]
            [self.modelCell setValue:model forKey:keyPath];
        }

因为大意找了半天才找到这个原因，我觉得可以在 sd_addSubviews 里判断如果某个view是nil就抛个异常。
