### ISSUE TITLE
能不能出个仿微信朋友圈的那种效果，有多个图片的情况

### ISSUE THREAD

**Issue by wfkbyni** [gsdios/SDAutoLayout#8]

**Comment by gsdios** [comment]
近期会更新

**Comment by wfkbyni** [comment]
大概还有好久呢？

**Comment by gsdios** [comment]
朋友圈 下周一前上传，高仿微信 下周上传

**Comment by gsdios** [comment]
朋友圈demo已经上传

高仿微信计划：
1.高仿朋友圈
2.完善细节
3.高仿完整微信app

PS：第2和3步将在接下来的一周内完成，代码会持续在我的github更新（https://github.com/gsdios）。

**Comment by zuojx1013** [comment]
朋友圈里的评论如何实现？里面镶嵌tableview吗？
