### ISSUE TITLE
删除某个cell时，后面的布局不对

### ISSUE THREAD

**Issue by zhiaiing** [gsdios/SDAutoLayout#87]
删除某个cell时, 除了整个tableView reload外, 只单行删除时(整个tableView不刷新)后面cell的高度不对,有什么办法解决？   (刷新整个tableView 计算frame时间有点久)

**Comment by imWalsh** [comment]
我也有这个问题，不知道怎么解决

**Comment by gsdios** [comment]
已经实现删除某行cell时自动调整height缓存了，可以下载最新代码测试下，另外可以加入SDAutoLayout的QQ群497140713。

**Comment by imWalsh** [comment]
3Q

发自我的 iPhone

在 2016年6月23日，14:44，高少东 <notifications@github.com<mailto:notifications@github.com>> 写道：


已经实现删除某行cell时自动调整height缓存了，可以下载最新代码测试下，另外可以加入SDAutoLayout的QQ群497140713。

―

**Comment by zhiaiing** [comment]
最好把删除某个section时缓存的height也调整下()
- (void)sd_deleteSections:(NSIndexSet *)sections withRowAnimation:(UITableViewRowAnimation)animation；
