### ISSUE TITLE
能否出一个swift版本，谢谢

### ISSUE THREAD

**Issue by zj2050** [gsdios/SDAutoLayout#9]
能否出一个swift版本，谢谢

**Comment by gsdios** [comment]
后期会出的。

**Comment by gsdios** [comment]
现在 也可以在 swift使用的

**Comment by lumiao0113** [comment]
没有在swift中使用的教程说明呀

**Comment by iOSBeginner** [comment]
@lumiao0113 其實用法差不多
`_ = startButton.sd_layout().bottomSpaceToView(self.view, 200)?.centerXEqualToView(self.view)`

前面的「_ = 」只是因為你不加的話 swift 會警告你，說你 return 的 SDAutoLayoutModel 沒有用變數存起來，但我們不需要，所以加個「_ = 」就可以了。
