### ISSUE TITLE
- (void)sd_layoutSubviews方法一直在调用

### ISSUE THREAD

**Issue by xiaotaner** [gsdios/SDAutoLayout#91]
在使用了SDAutoLayout的view里，这个方法就一直在调用，即使我没有任何的操作。请问这样会有问题吗

**Comment by gsdios** [comment]
没有问题的，那个走的是你原来的view的layoutsubviews方法

**Comment by xiaotaner** [comment]
是的，我看了您的博客说是通过Method Swizzling交换了方法，我想了解一下为什么会重复调用（学习目的）

**Comment by liulei104** [comment]
崩到[self sd_layoutSubviews];这里，代码里没有关于layoutSubViews代码，什么原因？？？

**Comment by q563469** [comment]
我也是崩到[self sd_layoutSubviews];这里，代码里没有关于layoutSubViews代码，什么原因？？？
提示 [nsnull ...] uns...指向不可识别的内存。。。。
