### ISSUE TITLE
最大间距最小间距

### ISSUE THREAD

**Issue by qyzhaojinxi** [gsdios/SDAutoLayout#92]
请教一下，怎么设置最大间距最小间距呢？现在只是equal

**Comment by gsdios** [comment]
目前只可以额外设置偏移量，还没有最大间距或者最小间距，可以加入下SDAutoLayout的QQ群497140713。

**Comment by qyzhaojinxi** [comment]
偏移量指的就是space间隔吧？用现有的方式什么方式实现类似的效果么？ qq群已经加入了。
